# Generated by Django 3.2.6 on 2021-08-16 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentTaskList',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='LikeTaskList',
            new_name='Like',
        ),
    ]
