# Generated by Django 3.2.6 on 2021-08-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0002_auto_20210816_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
